plt.figure(figsize=(12,6))
plt.plot(data.index, data['Price'], label='Historical', marker='o')
plt.plot(future_df.index, future_df['PredictedPrice'], label='Forecast', marker='x', linestyle='--')
plt.title("Natural Gas Price Forecast (Next 12 Months)")
plt.xlabel("Date")
plt.ylabel("Price ($)")
plt.legend()
plt.grid(True)
plt.show()
